### ISSUE TITLE
When adding plugin to and empty new project lots of errors are reported

### ISSUE THREAD

**Issue by sancho2** [Maran23/script-ide#22] opened 2023-11-28 01:05 UTC
This is an excellent add-on and for me it is a must have.   
It works perfectly fine and the following errors disappear when the project is reloaded.     
I notice the following when installing this on an empty project ie no scenes or scripts:   

>   Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/class.svg-e6f2816a1f06041fb421c2af52817a4a.editor.meta'
>   Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/constant.svg-f6e857276565573c7540f3c32801842a.editor.meta'
>   Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/export.svg-d2d18132258a7a219ec1af1f0316c91c.editor.meta'
>   Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/func.svg-139842caa5b4b7e4839711b6c756d0f7.editor.meta'
>   Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/func_get.svg-093f0ce02889d1f102ff9cc3e7f72654.editor.meta'
>   Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/func_set.svg-c31168d90866ff1707ad9834754bd2c9.editor.meta'
>   Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/keyword.svg-15ea12cc9eda85ed385533fe57e3bba8.editor.meta'
>   Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/property.svg-9e228499f30651faad74aa99e4499d7e.editor.meta'
>   Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/signal.svg-97182e1498b520a1ff5b8b9017c3b480.editor.meta'
>      
  
Godot 4.2 dev5   
Ubuntu 20.04.6 LTS      
 
Thanks for this add-on.

**Comment by Maran23** [comment] 2023-11-28 08:20
Thanks for the kind words!
I will have a look, this might be related to Godot 4.2 dev5, maybe upgrading the import file is enough here.
Will check later. :)

**Comment by Maran23** [comment] 2023-11-28 23:34
Hmm, looks like this is not that easy to fix.
The very first time the plugin is installed, Godot detects that the cache is not yet initialized with the icons.

This will not happen if the icon is not changed in the editor. But we actually change the icons (e.g. we turn on the option that the icon should scale with the editor scale to properly support HiDPI).
Therefore Godot displays this errors. This may need a fix in Godot itself unfortunately. :(

**Comment by sancho2** [comment] 2023-11-29 02:59
Since it doesn't affect the functionality it isn't an important issue.   
It might freak out someone who installs it.      
I recommend maybe putting a note in the readme that the installer may see these errors.

**Comment by Maran23** [comment] 2023-11-30 08:11
That is a good idea! 
I will also check if this problem will also appear when cloning another repository wiht modified icocns. That would be easier to track down and fix in Godot.

**Comment by Maran23** [comment] 2023-12-02 22:50
Can reproduce this with a simple project. So I will report that to Godot at some point and keep this open so I do not forget about this issue.

**Comment by Maran23** [comment] 2023-12-06 20:09
Created: https://github.com/godotengine/godot/issues/85859

**Comment by Maran23** [comment] 2023-12-20 11:49
Created a PR: https://github.com/godotengine/godot/pull/86137
Will be fixed in Godot 4.3.

**Comment by Maran23** [comment] 2024-08-15 21:02
Godot 4.3 is out, so closing now as fixed in 4.3. :)

**Closed by Maran23** 2024-08-15 21:02 UTC
